apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: z5lx8dynu-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/z5lx8dynu-dotnet-basic-gitops